### ISSUE TITLE
Phar not compiling-

### ISSUE THREAD

**Issue by truestblue** [polyverse/polyscripted-php#5]
Php archive directory not building properly causing other issues. Need to address this and the build phar files-- and files being build with strings that are left unscrambled. Need single file transforming first.

**Comment by archisgore** [comment]
Just saw this error:
```
Parse error: syntax error, unexpected 'as' (T_STRING), expecting ')' in /php/php-src/ext/phar/phar.php on line 10
make: *** [ext/phar/phar.phar] Error 255
```

**Comment by truestblue** [comment]
@archisgore I have a good idea how to fix that error (basically transform the phar.php file and stop the makefile from copying over it) but it led to other compile issues that I still need to look into.

**Comment by truestblue** [comment]
phar compilation working within build-scrambled.sh
